# Based on https://mherman.org/blog/dockerizing-an-angular-app/
# base image
FROM node:20-alpine as builder

# removed this for now
# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@20.3.7

# add app
COPY . /app

# Build the project and copy the files
RUN npm run ng build -- --deploy-url=/ --c production

FROM nginx:alpine

# Copy custom nginx configuration
COPY ./.nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copy from the stage 1
COPY --from=builder /app/dist/OS2IoT-frontend /app

# Install gettext for envsubst
RUN apk add --no-cache gettext

# Setup for non-root execution
RUN chown -R 101:101 /app && \
    chown -R 101:101 /var/cache/nginx && \
    chown -R 101:101 /var/log/nginx && \
    touch /var/run/nginx.pid && \
    chown 101:101 /var/run/nginx.pid

# Switch to non-root user (nginx user = UID 101 on Alpine)
USER 101

EXPOSE 8080
EXPOSE 8081

# Substiture placeholders in env.template.js using environment variables overwrite env.js
CMD ["/bin/sh",  "-c",  "envsubst < /app/browser/assets/env.template.js > /app/browser/assets/env.js && exec nginx -g 'daemon off;'"]
