# Based on https://mherman.org/blog/dockerizing-an-angular-app/
# base image
FROM node:12-alpine as builder

# removed this for now
# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app

# Build the project and copy the files
RUN npm run ng build -- --deploy-url=/ --prod

FROM bitnami/nginx:latest

#!/bin/sh

COPY ./.nginx/nginx.conf /opt/bitnami/nginx/conf/server_blocks/frontend.conf

## Remove default nginx index page
# RUN rm -rf /app/*

# Copy from the stahg 1
COPY --from=builder /app/dist/OS2IoT-frontend /app

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["nginx", "-g", "daemon off;"]
